"""Added Subscribers table

Revision ID: 26122d9046c4
Revises: ac6f7b9c62b4
Create Date: 2021-03-08 20:23:26.892907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26122d9046c4'
down_revision = 'ac6f7b9c62b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscribers_email', table_name='subscribers')
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.create_index('ix_subscribers_email', 'subscribers', ['email'], unique=True)
    # ### end Alembic commands ###
