"""Added relationship

Revision ID: a5d1fc3a6276
Revises: 7d571d76dc3f
Create Date: 2021-03-08 11:58:49.104276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d1fc3a6276'
down_revision = '7d571d76dc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('blogs_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitches_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blogs_id'], ['id'])
    op.drop_column('comments', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitches_id_fkey', 'comments', 'blogs', ['pitches_id'], ['id'])
    op.drop_column('comments', 'blogs_id')
    # ### end Alembic commands ###
